"""removing true_label and is_correct attributes from the prediction model

Revision ID: 108bf64d634a
Revises: 52aabd3cb97b
Create Date: 2025-07-12 17:38:13.132754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108bf64d634a'
down_revision = '52aabd3cb97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('is_correct')
        batch_op.drop_column('true_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('true_label', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
