"""adding true_label attribute to the prediction model

Revision ID: 21cfa7958e5e
Revises: e537ccf98498
Create Date: 2025-07-13 14:39:15.157332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cfa7958e5e'
down_revision = 'e537ccf98498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('true_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('true_label')

    # ### end Alembic commands ###
