"""adding gender attribute to the user model, and adding (true_label, is_correct) attributes to the prediction model.

Revision ID: 52aabd3cb97b
Revises: 
Create Date: 2025-07-10 03:26:41.504723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52aabd3cb97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('true_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('is_correct')
        batch_op.drop_column('true_label')

    # ### end Alembic commands ###
